const KEY="thap-tai-san-v5";
const layers=[["Nền móng","Thanh khoản & quỹ dự phòng"],["Bảo vệ","Bảo hiểm & an toàn nợ"],["Ổn định","Tiền gửi & trái phiếu"],["Tăng trưởng","Quỹ, cổ phiếu, kinh doanh"],["Tích lũy lớn","BĐS, vàng, tài sản lớn"],["Tự do tài chính","Dòng tiền thụ động ≥ chi tiêu"]];
let S=JSON.parse(localStorage.getItem(KEY)||"null")||{
assets:[
{name:"Tiền mặt",type:"cash",value:500000000,cashflow:0,debt:0,layer:0},
{name:"Tiền gửi",type:"deposit",value:1000000000,rate:7,cashflow:0,debt:0,layer:2},
{name:"Cổ phiếu",type:"stock",value:1000000000,rate:5,cashflow:0,debt:0,layer:3},
{name:"Nhà cho thuê",type:"rental",value:5000000000,rent:20000000,cost:2000000,vacancy:0,debt:2500000000,loanRate:8,principal:10000000,layer:4},
{name:"Trái phiếu",type:"bond",value:1000000000,rate:9,cashflow:0,debt:0,layer:2}
],
income:80000000,expense:40000000,monthlyInvest:30000000,bonus:100000000,annualReturn:8,emergencyMonths:6,
loans:[{name:"Vay nhà",balance:2500000000,rate:8,principal:10000000,interest:0}],
goals:[{name:"Tự do tài chính",target:10000000000,deadline:"2033-09-01"}],
events:[],tab:"dashboard",lastCalc:new Date().toISOString()
};
function save(){S.lastCalc=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(S))}
function money(n){return new Intl.NumberFormat("vi-VN",{maximumFractionDigits:0}).format(Math.round(n||0))+" đ"}
function pct(n){return (n||0).toFixed(1)+"%"}
function monthsTo(date){return Math.max(0,Math.ceil((new Date(date)-new Date())/(30.4375*864e5)))}
function datef(x){return new Date(x).toLocaleDateString("vi-VN")}
function assetIncome(a){
 if(a.type==="rental")return Math.max(0,(+a.rent||0)*(1-(+a.vacancy||0)/100)-(+a.cost||0));
 if(["stock","bond","deposit"].includes(a.type))return (+a.value||0)*(+a.rate||0)/100/12;
 return +a.cashflow||0;
}
function totals(){
 const assets=S.assets.reduce((a,x)=>a+(+x.value||0),0);
 const debt=S.loans.reduce((a,x)=>a+(+x.balance||0),0)+S.assets.reduce((a,x)=>a+(+x.debt||0),0);
 const passive=S.assets.reduce((a,x)=>a+assetIncome(x),0);
 const loanInterest=S.loans.reduce((a,x)=>a+(+x.balance||0)*(+x.rate||0)/100/12,0);
 const assetLoanInterest=S.assets.reduce((a,x)=>a+(+x.debt||0)*(+x.loanRate||0)/100/12,0);
 const principal=S.loans.reduce((a,x)=>a+(+x.principal||0),0)+S.assets.reduce((a,x)=>a+(+x.principal||0),0);
 return {assets,debt,net:assets-debt,passive,loanInterest:loanInterest+assetLoanInterest,principal,flowIn:+S.income+passive,flowOut:+S.expense+loanInterest+assetLoanInterest+principal,surplus:+S.income+passive-S.expense-loanInterest-assetLoanInterest-principal};
}
function nav(){let ns=[["dashboard","Tổng quan"],["tower","Tháp"],["assets","Tài sản"],["cash","Dòng tiền"],["goals","Mục tiêu"]];document.getElementById("nav").innerHTML=ns.map(([id,t])=>`<button class="${S.tab===id?"active":""}" onclick="S.tab='${id}';save();render()">${t}</button>`).join("")}
function render(){nav();({dashboard,tower,assets,cash,goals}[S.tab]||dashboard)()}
function future(months,initial=totals().net,monthly=S.monthlyInvest,annual=S.annualReturn){
 const r=Math.pow(1+annual/100,1/12)-1;
 return initial*Math.pow(1+r,months)+monthly*(r?((Math.pow(1+r,months)-1)/r):months);
}
function goalPlan(g){
 const m=monthsTo(g.deadline), t=totals(), r=Math.pow(1+S.annualReturn/100,1/12)-1;
 const base=t.net*Math.pow(1+r,m), need=Math.max(0,(+g.target-base)*(r? r/(Math.pow(1+r,m)-1):1/Math.max(1,m)));
 const projected=future(m), gap=Math.max(0,+g.target-projected), extra=Math.max(0,need-S.monthlyInvest);
 return {m,base,need,projected,gap,extra,ok:projected>=+g.target};
}
function dashboard(){
 const t=totals(),g=S.goals[0],p=g?goalPlan(g):null;
 document.getElementById("app").innerHTML=`<div class="card hero">
 <div class="small">TÀI SẢN RÒNG HIỆN TẠI</div><div style="font-size:31px;font-weight:900;margin:4px 0 14px">${money(t.net)}</div>
 <div class="grid2"><div class="metric dark"><div class="label">Tổng tài sản</div><div class="v">${money(t.assets)}</div></div><div class="metric dark"><div class="label">Tổng nợ</div><div class="v">${money(t.debt)}</div></div></div></div>
 <div class="card"><div class="sectionhead"><h3>Dòng tiền tháng</h3><span class="tag">${t.surplus>=0?"Dương":"Âm"}</span></div>
 <div class="grid2"><div class="metric"><div class="label">Tổng thu</div><div class="v">${money(t.flowIn)}</div></div><div class="metric"><div class="label">Tổng chi</div><div class="v">${money(t.flowOut)}</div></div><div class="metric"><div class="label">Dòng tiền dư</div><div class="v">${money(t.surplus)}</div></div><div class="metric"><div class="label">Thu nhập thụ động</div><div class="v">${money(t.passive)}</div></div></div>
 <p class="small" style="margin-top:10px">Thu gồm lương + tiền thuê + cổ tức + lãi. Chi gồm sinh hoạt + lãi vay + gốc vay.</p></div>
 ${g?`<div class="card"><div class="sectionhead"><div><div class="small">MỤC TIÊU CHÍNH</div><h2>${g.name}</h2></div><span class="tag">${p.ok?"ĐẠT KẾ HOẠCH":"CẦN BỔ SUNG"}</span></div>
 <div class="grid2"><div class="metric"><div class="label">Mục tiêu</div><div class="v">${money(g.target)}</div></div><div class="metric"><div class="label">Dự kiến đạt</div><div class="v">${money(p.projected)}</div></div><div class="metric"><div class="label">Còn thiếu</div><div class="v">${money(p.gap)}</div></div><div class="metric"><div class="label">Cần tăng dòng tiền</div><div class="v">${money(p.extra)}/tháng</div></div></div>
 <div style="margin-top:12px"><div class="row small"><span>Tiến độ dự kiến</span><b>${Math.min(100,g.target?p.projected/g.target*100:0).toFixed(1)}%</b></div><div class="bar"><i style="width:${Math.min(100,g.target?p.projected/g.target*100:0)}%"></i></div></div>
 <p class="small" style="margin-top:9px">Hạn: ${datef(g.deadline)} • Lãi suất kỳ vọng: ${pct(S.annualReturn)}</p></div>`:`<div class="card"><h3>Chưa có mục tiêu</h3><button onclick="goalForm()">+ Tạo mục tiêu</button></div>`}
 <div class="card"><div class="sectionhead"><h3>Dự phóng 7 năm</h3><span class="small">Tự chạy theo thời gian</span></div><canvas id="chart"></canvas></div>
 <div class="card"><div class="sectionhead"><h3>Cập nhật dữ liệu</h3><span class="small">${datef(S.lastCalc)}</span></div><div class="actions"><button onclick="settings()">Lương & lãi suất</button><button class="secondary" onclick="S.tab='assets';render()">Tài sản</button><button class="secondary" onclick="S.tab='cash';render()">Khoản vay</button></div></div>`;
 draw("chart");
}
function tower(){let h=`<div class="card"><h2>Tháp Tài Sản</h2><p class="small">Mỗi tầng thể hiện vai trò của tài sản trong hành trình tự do tài chính.</p><div class="tower">`;for(let i=0;i<6;i++){let v=S.assets.filter(a=>+a.layer===i).reduce((x,a)=>x+(+a.value||0),0);h+=`<div class="layer ${i===5?"top":""}"><b>${i+1}. ${layers[i][0]}</b><div class="small">${layers[i][1]}</div><strong>${money(v)}</strong></div>`}h+=`</div></div><div class="card"><h3>Nền móng</h3><p>Quỹ dự phòng mục tiêu: <b>${money(S.expense*S.emergencyMonths)}</b></p><p>Nợ / tổng tài sản: <b>${pct(totals().debt/Math.max(1,totals().assets)*100)}</b></p></div>`;document.getElementById("app").innerHTML=h}
function typeName(t){return {cash:"Tiền mặt",deposit:"Tiền gửi",stock:"Cổ phiếu",bond:"Trái phiếu",rental:"BĐS cho thuê",other:"Khác"}[t]||"Khác"}
function assets(){let h=`<div class="card"><div class="sectionhead"><div><h2>Tài sản</h2><p class="small">Giá trị + dòng tiền + nợ gắn với tài sản.</p></div><button onclick="assetForm()">+ Thêm</button></div>`;S.assets.forEach((a,i)=>{h+=`<div class="item"><div class="row"><div><b>${a.name}</b><div class="small">${typeName(a.type)} • ${layers[a.layer][0]}</div></div><strong>${money(a.value)}</strong></div><p class="small">Dòng tiền: <b>${money(assetIncome(a))}/tháng</b>${a.rate?` • Tỷ suất: ${pct(a.rate)}`:""}${a.debt?` • Nợ: ${money(a.debt)}`:""}</p><button class="secondary" onclick="assetForm(${i})">Sửa</button> <button class="danger" onclick="delAsset(${i})">Xóa</button></div>`});h+=`</div><div class="card"><h3>Cách tính dòng tiền</h3><p class="small">BĐS: tiền thuê − chi phí − ảnh hưởng tỷ lệ trống. Cổ phiếu/trái phiếu/tiền gửi: giá trị × tỷ suất ÷ 12.</p></div>`;document.getElementById("app").innerHTML=h}
function assetForm(i=null){let a=i===null?{name:"",type:"cash",value:0,rate:0,rent:0,cost:0,vacancy:0,debt:0,loanRate:0,principal:0,layer:0}:S.assets[i];document.getElementById("app").innerHTML=`<div class="card"><h2>${i===null?"Thêm tài sản":"Sửa tài sản"}</h2><label>Tên</label><input id="xname" value="${a.name}"><label>Loại</label><select id="xtype">${Object.entries({cash:"Tiền mặt",deposit:"Tiền gửi",stock:"Cổ phiếu",bond:"Trái phiếu",rental:"BĐS cho thuê",other:"Khác"}).map(([k,v])=>`<option value="${k}" ${a.type===k?"selected":""}>${v}</option>`).join("")}</select><label>Giá trị</label><input id="xvalue" type="number" value="${a.value}"><label>Tỷ suất/năm (%) — cổ tức, coupon, lãi suất tiền gửi</label><input id="xrate" type="number" step="0.1" value="${a.rate||0}"><label>Tiền thuê/tháng (chỉ BĐS cho thuê)</label><input id="xrent" type="number" value="${a.rent||0}"><label>Chi phí/tháng</label><input id="xcost" type="number" value="${a.cost||0}"><label>Tỷ lệ trống (%)</label><input id="xvac" type="number" value="${a.vacancy||0}"><label>Nợ gắn với tài sản</label><input id="xdebt" type="number" value="${a.debt||0}"><label>Lãi vay (%/năm)</label><input id="xloanrate" type="number" step="0.1" value="${a.loanRate||0}"><label>Gốc trả/tháng</label><input id="xprincipal" type="number" value="${a.principal||0}"><label>Tầng Tháp</label><select id="xlayer">${layers.map((l,k)=>`<option value="${k}" ${k===+a.layer?"selected":""}>${k+1}. ${l[0]}</option>`).join("")}</select><br><br><button onclick="saveAsset(${i===null?"null":i})">Lưu</button> <button class="secondary" onclick="S.tab='assets';render()">Hủy</button></div>`}
function saveAsset(i){let a={name:xname.value||"Tài sản",type:xtype.value,value:+xvalue.value||0,rate:+xrate.value||0,rent:+xrent.value||0,cost:+xcost.value||0,vacancy:+xvac.value||0,debt:+xdebt.value||0,loanRate:+xloanrate.value||0,principal:+xprincipal.value||0,layer:+xlayer.value||0};if(i===null)S.assets.push(a);else S.assets[i]=a;S.events.push({date:new Date().toISOString(),text:"Cập nhật tài sản: "+a.name});save();S.tab="assets";render()}
function delAsset(i){if(confirm("Xóa tài sản?")){S.assets.splice(i,1);save();render()}}
function cash(){let t=totals();let h=`<div class="card"><div class="sectionhead"><div><h2>Dòng tiền & Khoản vay</h2><p class="small">Gốc và lãi được tách riêng.</p></div><button onclick="settings()">Cập nhật</button></div><div class="grid2"><div class="metric"><div class="label">Tổng thu</div><div class="v">${money(t.flowIn)}</div></div><div class="metric"><div class="label">Tổng chi</div><div class="v">${money(t.flowOut)}</div></div><div class="metric"><div class="label">Lãi vay/tháng</div><div class="v">${money(t.loanInterest)}</div></div><div class="metric"><div class="label">Gốc vay/tháng</div><div class="v">${money(t.principal)}</div></div></div></div><div class="card"><div class="sectionhead"><h3>Khoản vay</h3><button onclick="loanForm()">+ Thêm</button></div>`;S.loans.forEach((l,i)=>{let interest=l.balance*l.rate/100/12;h+=`<div class="item"><div class="row"><b>${l.name}</b><strong>${money(l.balance)}</strong></div><p class="small">Lãi ${money(interest)}/tháng • Gốc ${money(l.principal)}/tháng • Tổng trả ${money(interest+l.principal)}/tháng</p><button class="secondary" onclick="loanForm(${i})">Sửa</button> <button class="danger" onclick="S.loans.splice(${i},1);save();render()">Xóa</button></div>`});h+=`</div>`;document.getElementById("app").innerHTML=h}
function loanForm(i=null){let l=i===null?{name:"Khoản vay mới",balance:0,rate:0,principal:0}:S.loans[i];document.getElementById("app").innerHTML=`<div class="card"><h2>${i===null?"Thêm khoản vay":"Sửa khoản vay"}</h2><label>Tên khoản vay</label><input id="ln" value="${l.name}"><label>Dư nợ hiện tại</label><input id="lb" type="number" value="${l.balance}"><label>Lãi suất (%/năm)</label><input id="lr" type="number" step="0.1" value="${l.rate}"><label>Gốc trả/tháng</label><input id="lp" type="number" value="${l.principal}"><br><br><button onclick="saveLoan(${i===null?"null":i})">Lưu</button> <button class="secondary" onclick="S.tab='cash';render()">Hủy</button></div>`}
function saveLoan(i){let l={name:ln.value||"Khoản vay",balance:+lb.value||0,rate:+lr.value||0,principal:+lp.value||0};if(i===null)S.loans.push(l);else S.loans[i]=l;S.events.push({date:new Date().toISOString(),text:"Cập nhật khoản vay: "+l.name});save();S.tab="cash";render()}
function settings(){document.getElementById("app").innerHTML=`<div class="card"><h2>Thông số dòng tiền</h2><label>Lương/thu nhập tháng</label><input id="si" type="number" value="${S.income}"><label>Chi tiêu tháng</label><input id="se" type="number" value="${S.expense}"><label>Tiền đầu tư thêm/tháng</label><input id="sm" type="number" value="${S.monthlyInvest}"><label>Thưởng/năm</label><input id="sb" type="number" value="${S.bonus||0}"><label>Lãi suất/tỷ suất kỳ vọng (%/năm)</label><input id="sr" type="number" step="0.1" value="${S.annualReturn}"><label>Quỹ dự phòng (tháng)</label><input id="sf" type="number" value="${S.emergencyMonths}"><br><br><button onclick="saveSettings()">Lưu thay đổi</button></div><div class="card"><h3>Sao lưu dữ liệu</h3><p class="small">Xuất/khôi phục toàn bộ tài sản, dòng tiền, khoản vay, lịch sử và mục tiêu.</p><button onclick="exportData()">Xuất backup</button><br><br><input type="file" accept=".json,application/json" onchange="importData(event)"></div>`}
function saveSettings(){S.income=+si.value||0;S.expense=+se.value||0;S.monthlyInvest=+sm.value||0;S.bonus=+sb.value||0;S.annualReturn=+sr.value||0;S.emergencyMonths=+sf.value||6;S.events.push({date:new Date().toISOString(),text:`Cập nhật dòng tiền: thu ${money(S.income)}, chi ${money(S.expense)}, đầu tư ${money(S.monthlyInvest)}, lãi suất ${pct(S.annualReturn)}`});save();S.tab="dashboard";render()}
function goals(){let h=`<div class="card"><div class="sectionhead"><div><h2>Mục tiêu</h2><p class="small">Mục tiêu được tính lại ngay khi dữ liệu thay đổi.</p></div><button onclick="goalForm()">+ Thêm</button></div>`;S.goals.forEach((g,i)=>{let p=goalPlan(g);h+=`<div class="item"><div class="row"><b>${g.name}</b><span class="tag">${p.ok?"Đạt":"Thiếu"}</span></div><p>Mục tiêu <b>${money(g.target)}</b> • Hạn ${datef(g.deadline)}</p><p>Dự kiến <b>${money(p.projected)}</b> • Còn thiếu <b>${money(p.gap)}</b></p><p>Cần tăng dòng tiền: <b>${money(p.extra)}/tháng</b></p><button class="secondary" onclick="goalForm(${i})">Sửa</button> <button class="danger" onclick="S.goals.splice(${i},1);save();render()">Xóa</button></div>`});h+=`</div>`;document.getElementById("app").innerHTML=h}
function goalForm(i=null){let g=i===null?{name:"Mục tiêu mới",target:10000000000,deadline:"2033-09-01"}:S.goals[i];document.getElementById("app").innerHTML=`<div class="card"><h2>${i===null?"Tạo mục tiêu":"Sửa mục tiêu"}</h2><label>Tên mục tiêu</label><input id="gn" value="${g.name}"><label>Số tiền mục tiêu</label><input id="gt" type="number" value="${g.target}"><label>Hạn mục tiêu</label><input id="gd" type="date" value="${g.deadline}"><br><br><button onclick="saveGoal(${i===null?"null":i})">Lưu</button> <button class="secondary" onclick="S.tab='goals';render()">Hủy</button></div>`}
function saveGoal(i){let g={name:gn.value||"Mục tiêu",target:+gt.value||0,deadline:gd.value};if(i===null)S.goals.push(g);else S.goals[i]=g;save();S.tab="goals";render()}
function exportData(){let p={app:"Tháp Tài Sản",version:"5.0",exportedAt:new Date().toISOString(),data:S},b=new Blob([JSON.stringify(p,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="thap-tai-san-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(u)}
function importData(e){let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let p=JSON.parse(r.result),d=p.data||p;if(!Array.isArray(d.assets)||!Array.isArray(d.goals)||!Array.isArray(d.loans))throw 0;if(confirm("Khôi phục sẽ thay toàn bộ dữ liệu hiện tại. Tiếp tục?")){S=d;S.tab="dashboard";save();render();alert("Đã khôi phục.")}}catch{alert("File backup không hợp lệ.")}};r.readAsText(f)}
function draw(id){let c=document.getElementById(id);if(!c)return;let d=devicePixelRatio||1,w=c.clientWidth,h=210;c.width=w*d;c.height=h*d;let x=c.getContext("2d");x.scale(d,d);let pts=[];for(let m=0;m<=84;m+=6)pts.push(future(m)/1e9);let max=Math.max(...pts,1),p=25;x.beginPath();pts.forEach((v,i)=>{let X=p+i*(w-2*p)/(pts.length-1),Y=h-p-v/max*(h-2*p);i?x.lineTo(X,Y):x.moveTo(X,Y)});x.stroke();x.fillText("0",4,h-p+4);x.fillText(max.toFixed(1)+" tỷ",4,16);x.fillText("7 năm",w-p-30,h-5)}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});save();render();